FROM python:3.9.16-alpine as build
WORKDIR /app
COPY . .
RUN pip install mkdocs
RUN mkdocs build 
WORKDIR /app/site

FROM python:3.9.16-alpine 
WORKDIR /app
COPY --from=build /app/site . 
WORKDIR /app/site 
EXPOSE 8080
CMD python -m http.server 8080