name: Build operations
on:
  push:
    branches: 
      - main
      - dev
    tags:
      - '**'
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: get repository
        uses: actions/checkout@v3
      - run : ls -al
      - run : echo 'build image'
      - run : docker build -t cityhunterxx/website:v0 .
      - run : printenv 